.TH MICELIA 1 "August 2023" "Mycelia CLI Manual"
.SH NAME
micelia \- Manage files and directories with ease
.SH SYNOPSIS
.B micelia
[\fIOPTIONS\fR] \fIPATH\fR
.SH DESCRIPTION
\fImicelia\fR is a command-line tool that helps you manage files and directories efficiently. It allows you to perform various operations on the specified path.
.SH OPTIONS
.TP
.BR -i ", " --ignore " \fIIGNORE_PATH\fR"
Ignore the specified path during operations.
.TP
.BR -h ", " --help"
Display this help message.
.SH EXAMPLES
\fBmicelia\fR -i /path/to/ignore /path/to/manage
.PP
This example will manage the path \fI/path/to/manage\fR while ignoring the path \fI/path/to/ignore\fR.
.SH SEE ALSO
Online documentation at https://yourwebsite.com/micelia
.SH BUGS
Report bugs to the issue tracker at https://github.com/yourusername/micelia/issues
.SH AUTHOR
Written by Your Name.
.SH COPYRIGHT
Copyright \(co 2023 Your Name.
.SH LICENSE
This program is distributed under the terms of the MIT License.
.SH DISCLAIMER
This manual page documents the \fImicelia\fR command. It may not contain comprehensive information about all command options and functionality.

