.TH MICELIA 1 "August 2023"
.SH NAME
micelia \- a naive SLOC counter
.SH SYNOPSIS
.B micelia
[\fIOPTIONS\fR] \fIPATH\fR
.SH DESCRIPTION
\fImicelia\fR is a simple command-line tool designed to count the number of source lines of code in a given \fIPATH\fR.
.SH OPTIONS
.TP
.B \-i, \-\-ignore \fIIGNORE_PATH\fR
.RS 10
ignore a specific \fIIGNORE_PATH\fR during the SLOC count.
.RE
.B \-h, \-\-help
.RS 10
display a help message describing the usage and available options of the \fImicelia\fR command.
.SH EXAMPLES
.B micelia .
.RS 10
count SLOC in current directory.
.RE
.B micelia \-i tests . 
.RS 10
count SLOC while ignoring the "tests" directory.
.SH AUTHOR
written by \fIdrainpixie\fR.
.SH CAVEATS
this tool employs a naive approach to counting source lines of code and may not accurately reflect the complexity or quality of a codebase. Use it as a basic metric for code size assessment.

